--- #YAML:1.0
name:               CVS-Metrics
version:            0.18
abstract:           Utilities for process cvs log
author:
    - Francois PERRAD <francois.perrad@gadz.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Chart::Plot::Canvas:  0
    GD:                   0
    GD::Graph:            0
    HTML::Template:       0
    Parse::RecDescent:    0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
